apiVersion: v2
name: openshift-pipelines-operator
description: A Helm chart to deploy the Red Hat OpenShift Pipelines Operator
type: application
version: 0.1.0
appVersion: "1.20.1"

keywords:
  - openshift-pipelines
  - operator
  - tekton

home: https://www.redhat.com/es/technologies/cloud-computing/openshift/pipelines
