apiVersion: v2
name: authorino-operator
description: A Helm chart to deploy the Authorino Operator
type: application
version: 0.1.0
appVersion: "1.2.4"

keywords:
  - authorino
  - operator
  - security
  - authentication
  - openshift
  - kubernetes

home: https://github.com/kuadrant/authorino
sources:
  - https://github.com/kuadrant/authorino-operator
