apiVersion: v2
name: gitea-operator
description: A Helm chart to deploy the Gitea Operator (RHPDS)
type: application
version: 0.1.0
appVersion: "2.1.0"

keywords:
  - gitea
  - operator
  - rhpds
  - git
  - scm
  - devtools
  - openshift

sources:
  - https://github.com/rhpds/gitea-operator
