apiVersion: v2
name: serverless-operator
description: A Helm chart to deploy the Red Hat OpenShift Serverless Operator
type: application
version: 0.1.0
appVersion: "1.37.0"

keywords:
  - openshift
  - operator
  - serverless

home: https://www.redhat.com/en/technologies/cloud-computing/openshift/serverless
