apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "minio.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "minio.name" . }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-secret
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-secret
                  key: minio_root_password
          args:
            - server
            - /data
            - --console-address=:{{ .Values.service.ports.console }}
          ports:
            - name: api
              containerPort: {{ .Values.service.ports.api }}
            - name: console
              containerPort: {{ .Values.service.ports.console }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "minio.fullname" . }}-pvc
