apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secret
type: Opaque
stringData:
  minio_root_user: {{ .Values.auth.rootUser | quote }}
  minio_root_password: {{ .Values.auth.rootPassword | quote }}
