apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "minio.name" . }}
  ports:
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: api
    - name: console
      port: {{ .Values.service.ports.console }}
      targetPort: console
